"""Removed tags Field from Todo

Revision ID: 0a548780bbbc
Revises: 278218950f62
Create Date: 2022-08-22 09:13:17.243040

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0a548780bbbc'
down_revision = '278218950f62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('tags', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
